json:{
  "unsmarten_punctuation": false, 
  "minimum_line_height": 120.0, 
  "extra_css": null, 
  "remove_paragraph_spacing": false, 
  "keep_ligatures": false, 
  "linearize_tables": false, 
  "subset_embedded_fonts": false, 
  "embed_all_fonts": false, 
  "expand_css": false, 
  "line_height": 0.0, 
  "transform_css_rules": "[]", 
  "insert_blank_line": false, 
  "input_encoding": null, 
  "filter_css": "", 
  "disable_font_rescaling": false, 
  "embed_font_family": "Droid Sans", 
  "remove_paragraph_spacing_indent_size": 1.5, 
  "change_justification": "original", 
  "insert_blank_line_size": 0.5, 
  "smarten_punctuation": false, 
  "font_size_mapping": null, 
  "asciiize": false, 
  "base_font_size": 0.0
}