#!/usr/bin/env zsh

## ---------------------------------------------------------------------------- #
## MOVE-LIST-JUMP
## ---------------------------------------------------------------------------- #
## DESC: Zsh directory module from prezto. It works like fast temporary bookmarks. 
##       Visit a dir press d then change dir. Press d again.
## LINK: https://github.com/sorin-ionescu/prezto/blob/master/modules/directory/init.zsh
1='cd +1'
2='cd +2'
3='cd +3'
4='cd +4'
5='cd +5'
6='cd +6'
7='cd +7'
8='cd +8'
9='cd +9'
d='dirs -v'
